### ISSUE TITLE
ignored null byte in input

### ISSUE THREAD

**Issue by camjac251** [onedr0p/qbittorrent-prune#4]
Do you get this error when running the script? It can run fine with it but I was hoping to log the output and these lines would be added to each new output.

```
./qbittorrent-prune.sh: line 74: warning: command substitution: ignored null byte in input
./qbittorrent-prune.sh: line 74: warning: command substitution: ignored null byte in input
```

**Comment by onedr0p** [comment]
I do not receive this warning, odd.
