### ISSUE TITLE
Mapping to Radarr/Sonarr

### ISSUE THREAD

**Issue by camjac251** [onedr0p/qbittorrent-prune#5]
This might be a little advanced and beyond the intent of the script but I've been trying to find something like this for Deluge before switching and this does half of it.

Would it be possible to have torrents mapped between Radarr/Sonarr and when a file becomes unregistered on qtBittorrent, the script would then delete the file locally in Radarr/Sonarr and search for the release again? This could help in places where proper isn't added to a release

There was some API stuff done over here (seems like the pastebin link expired though which would've been helpful) https://github.com/springjools/deluge-autoremoveplus/issues/5

**Comment by onedr0p** [comment]
Interesting idea! One thing that makes it tough is linking the torrent file to a movie / episode in Sonarr or Radarr

I think I need to also rewrite this in a proper programming language like Python or Go

**Comment by onedr0p** [comment]
This is definitely outside the scope of the project, and I have no idea if I'll ever get time to implement such an advanced feature.
